#!/usr/bin/env python3
"""Generate Pi support files from the skill sources.

Reads skills/*/SKILL.md (the same sources the Claude plugin ships) and writes
extensions/styles.generated.ts, so the /style extension injects byte-identical
wording to the on-demand skills. Re-run after pulling upstream style updates:

    python3 scripts/gen-pi.py

Also syncs package.json "version" from VERSION (e.g. 0.8 -> 0.8.0).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STYLES = ["attention-kind", "spartan", "rundown"]


def body_of(skill_path: Path) -> str:
    text = skill_path.read_text()
    return re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL).strip()


def ts_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def main() -> int:
    version = (ROOT / "VERSION").read_text().strip()
    bodies = {}
    for slug in STYLES:
        src = ROOT / "skills" / slug / "SKILL.md"
        if not src.exists():
            print(f"missing {src}", file=sys.stderr)
            return 1
        bodies[slug] = body_of(src)

    out = [
        "// GENERATED by scripts/gen-pi.py from skills/*/SKILL.md. Do not edit.",
        f"// attention-span v{version} · https://github.com/alexgreensh/attention-span",
        "",
        f'export const ATTENTION_SPAN_VERSION = "{version}";',
        "",
        "export const STYLE_BODIES: Record<string, string> = {",
    ]
    for slug in STYLES:
        out.append(f'  "{slug}": `{ts_escape(bodies[slug])}`,')
    out.append("};")
    out.append("")

    ext_dir = ROOT / "extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    (ext_dir / "styles.generated.ts").write_text("\n".join(out))
    print(f"wrote extensions/styles.generated.ts ({len(bodies)} styles, v{version})")

    pkg_path = ROOT / "package.json"
    if pkg_path.exists():
        pkg = json.loads(pkg_path.read_text())
        parts = version.split(".")
        semver = version if len(parts) == 3 else f"{version}.0" if len(parts) == 2 else None
        if semver and pkg.get("version") != semver:
            pkg["version"] = semver
            pkg_path.write_text(json.dumps(pkg, indent=2) + "\n")
            print(f"synced package.json version to {semver}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
